KrumpetPirate/AAXtoMP3

AAXtoMP3.sh

First of all thank you a lot for the script. It saves me a lot of time and works pretty reliably. Nevertheless I have two suggestions.
Bash may be installed in a different path. On Mac OS it lives in `/bin/bash` for example.

Comply with bash being installed in a different path

---

AAXtoMP3.sh

Secondly sed's -r switch is not portable. I'm using -e to achieve the same goal.
https://www.gnu.org/software/sed/manual/html_node/Invoking-sed.html#Invoking-sed

Don't use -r switch on sed as it's not portable

---

AAXtoMP3.sh

This patch fixes #11 and prevents the following error, which happens when a title contains a single quote (e.g. this `tmp.txt` file: https://gist.github.com/pbowyer/7b7d2181da42c4de1d4f947247a47178):
```
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
```

Fix for titles with single quotes breaking script

---

AAXtoMP3.sh

- Add check for ffpmeg command, fail if it's missing
- Use parenthesis instead of backticks - BashFAQ/082 / shellcheck SC2006
- Use `xargs echo` vs bare `xargs` to prevent execution of commands that appear in the title
- Echo date with status updates
- Safe quotes - shellcheck SC2086
- Consistent variable braces
- use `read -r` to safely handle slashes - shellcheck SC2162
- trap exit and cleanup tmp.txt

General cleanup

---

AAXtoMP3.sh

Quotes are required for rm to properly parse the params. Otherwise spaces separate the file path into several params and the script dies.

Fix deleting full audio file in chaptered mode

---

AAXtoMP3.sh

The changes were quite simple – mainly shortening command flags. Note that I only have this one OSX machine to try it on, I cannot make sure that those changes are compatible with other systems. Proceed with caution.
- Use shorthand flags for `rm`: `-r` instead of `--recursive`, `-f` instead of `--force`
- Add fallback for `mktemp`. See http://unix.stackexchange.com/a/84980
- Use shorthand flags for `cut`: `-d` instead of `--delimiter`, `-f` instead of `--fields`
Tested on OSX 10.11.6 El Capitan

Make the script OSX compatible

---

AAXtoMP3.sh

Prevent ffmpeg from showing "Enter command: <target>|all <time>|-1 <command>[ <argument>]" in bash, tested on Ubuntu 16.06, ffmpeg version 2.8.11
Reference: https://unix.stackexchange.com/a/36411/178221

Prevent ffmpeg from showing "Enter command: <target>|all <time>|-1 <command>[ <argument>]" in bash

---

AAXtoMP3

As discussed in https://github.com/KrumpetPirate/AAXtoMP3/issues/26 I've added a quick and dirty fix to add chapter padding (for audio books containing up to 999 chapters) for non-single conversion mode.

Added chapter padding

---

AAXtoMP3

Amazon actually does use some other strings as chapter-title than "Chapter <n>". ("Kapitel <n>" in german, for example.)
Getting $chaptercount wrong stops the script and breaks the chapter splitting and cover extraction. (Because of -o errexit i guess.)
grep'ing for the actual chapter line in the metadata.txt for counting chapters seems to be the better way.

Fix chaptercount for 0-padding

---

AAXtoMP3

Doesn't reencode like the other options, so may be useful for some people.

Add support for copying to m4b (no reencode)

---

AAXtoMP3

this adds support for transcoding to OPUS. it seems like ffmpeg still has some issues with the native opus container format (*.opus), so let's use the OGG container format for now.

add support for the opus codec

---

AAXtoMP3

Hi,
thanks for AAtoMP3.
This change uses an authcode file located in the users HOME directory ($HOME/.authcode) instead of a local one .authcode file in the git directory. It seemed more convenient at the time. Minor drawback: lack of multi-audible-account support.
Signed-off-by: Me <corbolais@gmail.com>

chg: use authcode file located in HOME dir.

---

AAXtoMP3

The HOME environment variable is not set on Windows by default. Instead Windows uses USERPROFILE. It is possible for HOME to be set on Windows but for users who have not done this they will get: `HOME: unbound variable`. I have added a line that sets HOME to USERPROFILE if HOME is missing and USERPROFILE is found. This solves the unbound variable error.
I've tested this on Windows 10 using MinGW 6.2 - works perfectly other than the MAX_PATH on windows is much shorter than on other OS's meaning the output audio file tends to have a path that is too long: `$(dirname "${path}")/${genre}/${artist}/${title}/${title}.${extension}` The title is sometimes egregiously long on some audio-books.

Fixed HOME environment variable missing under Windows

---

AAXtoMP3

sed operations were failing on mac os x; this patch follows the grep example for the fix.

check for GNU sed, recommend gnu-sed for mac os x if missing

---

README.md

On a stock Ubuntu 16.04 server install, bc is not present, and splitting into chapter files fails.

Add bc to Ubuntu package list

---

README.md

The arguments `-aac` and `-em4b` did not exist.
Just changed them to the according options: `--aac` and `-e:m4b`.

Fix --chaptered usage example

---

AAXtoMP3

This is further to commit 61cb5b43d8e0a2da052fe0ddcdc1478ed6b497f9 .  It would be good if `bc` can also be added to the install-prompts suggested by the script when it detects some packages missing.

Also add bc to apt-get install list as prompted by script

---

AAXtoMP3

- Changes "container" for m4a and m4b to "mp4" as that is
the official container type.
- Changes "extension" checks for m4b to "container" checks
which check for "mp4". This makes it possible to produce
chaptered m4a files as well.
- Needs awk, but I think portable awk code is used. This
should probably be tested on other platforms, like macOS.
- Adds a check for mp4chaps, but that should be included
in the same package as mp4art.
- Only adds chapter data to mp4 files if using single-file
output mode.
- Removes the need for renaming files from m4a to m4b.
I did not test this on macOS as I do not have access to that system.

Create chaptered single-file m4a's/m4b's

---

AAXtoMP3
README.md

So the user can abort if the target directory would be overwritten.
Pork:  Remove trailing whitespace

Add no-clobber option to CLI

---

AAXtoMP3

On linux, file name max length is 143 characters. I put a limit to title file name as a fix max name to 100 characters to avoid error and process abortion

Fix mkdir: cannot create directory : File name too long 

---

AAXtoMP3

Forcibly add the track and title metadata to the audio stream.  Fixes missing meta-data with Plex and possibly other programs.
Use the .opus file extension and ogg container for opus files to match recommended practice, and correct detection of opus files in Plex and other programs

Small updates for Opus and metadata

---

AAXtoMP3

As I mentioned in #127 the app I use has problems, if the chaptered files still hold menu metadata.
I'm not very experienced in this area but for me this menu metadata is not useful, if I have chaptered files.
So this PR removes the menu metadata from the chaptered files. Let me know if this has some unwanted side effects, but my tests with `-e:m4b -c`worked for me.

Remove chapter metadata in "chaptered mode"

---

AAXtoMP3
README.md

Until now, when the conversion of a audiobook gets interrrupted during the splitting phase, one has to delete all the output files and restart from beginning.
This can be very uncomfy, especially if it's a long audiobook and the computer did work on it for several hours.
I added some changes, so that one only has to delete the last (incompletely generated) chapter and add "--continue " to the command where CHAPTERNUMBER is the chapter, that has been interrupted while splitting of.
For this to work I mainly just skipped the steps which were already done before interruption with if-conditions.

Continue after interruption

---

AAXtoMP3

As discussed in #126, this commit uses `mediainfo` (as optional dependency) to parse additional metadata tags (`description` and `narrator` for now)

Use mediainfo to parse additional metadata

---

README.md

On my computer --chaptered does work for flac as well, maybe my last pull request fixed this issue as well.
So I've updated the README. Maybe somebody else checks, whether this works on his computer as well, before merging this in.
I'm planning to add manual flac compression level choice as my next contribution. Maybe I'll try it this evening.
Right now its allways on default (5).

Updated README since chaptered mode works for flac as well

---

AAXtoMP3

If we just use `return` and the file `$media_file` (the aax file) is not readable, the script continues until an error.
Instead we `return 1` so `errexit` takes care of quitting

Exit if no aax file is found

---

AAXtoMP3
README.md

As written in the headline I added compression levels for mp3, opus and flac.
`--level <COMPRESSIONLEVEL>`
mp3: 0-9 where 0 is highest quality
opus: 0-10 where 10 is highest quality
flac: 0-12 where 12 is highest compression
Invalid values or applying level to other codecs results in an error message.

Added compression levels for mp3, opus and flac

---

AAXtoMP3
README.md

Two additional flags for customizing author metadata
* `--keep-author`:           If a book has multiple authors and you don't want all of them in the metadata, with this flag you can specify a specific author (1 is the first, 2 is the second...) to keep while discarding the others.
* `--author`:                    Manually set the author metadata field, useful if you have multiple books of the same author but the name reported is different (eg. spacing, accents..). Has precedence over `--keep-author`.

Author customization

---

AAXtoMP3
README.md

The following flags can modify the default naming scheme:
* **--dir-naming-scheme** or **-D**  
* **--file-naming-scheme** or **-F** 
* **--chapter-naming-scheme** 
Each flag takes a string as argument. If the string contains a variable defined in the script (eg. artist, title, chapter, narrator...), the corresponding value is used.
The default options correspond to the following flags:
* `--dir-naming-scheme '$genre/$artist/$title'`
* `--file-naming-scheme '$title'`
* `--chapter-naming-scheme '$title-$(printf %0${#chaptercount}d $chapternum) $chapter'`

Custom naming scheme

---

AAXtoMP3

More information in issue #155

 Fix for issue KrumpetPirate#155

---

AAXtoMP3

The `fileNameScheme` is empty by default, so the file generated is named only `.chapters.txt` if -F is not specified.
Provided with the filename `mp4file`, mp4chaps searches for a file named `<mp4file>.chapters.txt`.

Use the current filename scheme

---

AAXtoMP3
README.md
interactiveAAXtoMP3

This script interactively asks the user for the options to call AAXtoMP3 with.
I only implemented codec, compression, chapters, authcode, loglevel and source file because I wanted the dialog to be short.
If wanted the other options can be added. Preferably in a way that they only appeare if `--advanced` is used.

Call AAXtoMP3 interactively

---

AAXtoMP3

I wonder if it doesn't make sense to continue with the remaining files if one of them has already been fully processed.
This way the script can continue to run and you don't have to manually check which file is not finished yet?

Continue if the current file already exists

---

AAXtoMP3

When attempting to convert
https://www.audible.com/pd/Stephen-Fry-Presents-a-Selection-of-Anton-Chekhovs-Short-Stories-Audiobook/B0036GPPWS
using this tool and chaptered mode, ffmpeg fails out with
[libx264 @ 0x5588ef28d780] width not divisible by 2 (483x500)
Error initializing output stream 0:1 -- Error while opening encoder
for output stream #0:1 - maybe incorrect parameters such as bit_rate,
rate, width or height
Conversion failed!
This is because the cover file embedded in the downloaded mp4 file
from Audible has the dimensions 483x500. Found the extra_crop_cover
that's currently being used only for covers from the Audible CLI
tool and extended the script to instead check the dimensions of the
cover file and include the extra_crop_cover anytime the cover has an
odd width.

Add extra_crop_cover to All Odd Cover Widths

---

AAXtoMP3

I'm on MacOS and I have `grep` brew installed (aliased as `ggrep` as noted in this script) and I was getting `invalid option -- P`. Noticed a few places weren't using the `$GREP` variable that's meant to solve this issue.

Use GREP variable everywhere

---

AAXtoMP3

Replaces the `,000` in the chapters.txt file with `.000` to allow processing with `mp4chaps`

Fixing `,000` issue with mp4chaps

---

AAXtoMP3
README.md

Use ffmpeg to cover add instead of mp4art from deprecated mp4v2-utils package
closes: https://github.com/KrumpetPirate/AAXtoMP3/issues/198

feat: Use ffmpeg to cover add instead of mp4art

---

AAXtoMP3

Fixes #184
Adds a reduce + flatten step to generate a flat list of chapters.
Fixes #206
Support for emitting timestamps greater than 24 hours.
See https://jqplay.org/s/pcLohUSDGZ for test.

Fixes for jq command generating chapters.txt

---

AAXtoMP3

This change allow multiple covers of different audiobooks in the same target directory.

Change cover.jpg to $currentFileNameScheme.jpg

---

AAXtoMP3

Fixes #210.
I think this is more like a hack, but it does produce more sensible results.

Limit result to one line when parsing cover size.
